name: Publish to NPM Registry
on:
  workflow_dispatch:

jobs:
  publish:
    environment: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v2
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Install packages
        shell: bash
        run: |
          bun install --frozen-lockfile

          if ! test -z "`git diff --stat`"; then
            echo "Changes were found; please run 'bun install' and commit the output."
            echo
            git diff --name-only
            exit 1
          fi

      - name: Build
        run: bun run compile

      - name: Publish package on NPM 📦
        run: |
          npm publish

